services:
  nginx:
    image: nginx:alpine
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    ports:
      - "${HOST_MACHINE_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./.docker-settings/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./.docker-settings/php/Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}-php"
    volumes:
      - ./src:/var/www/html
      - ./.docker-settings/php/limits.ini:/usr/local/etc/php/conf.d/limits.ini
      - ./.docker-settings/php/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      - ./.docker-settings/php/xhprof.ini:/usr/local/etc/php/conf.d/docker-php-ext-xhprof.ini
    environment:
      XHPROF_ENABLED: true
      PROFILER_ENDPOINT: http://profiler@buggregator:8000
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 start_with_request=yes"
    depends_on:
      - database      
    extra_hosts:
      - "host.docker.internal:host-gateway"
  buggregator:
    image: ghcr.io/buggregator/server:latest
    container_name: ${COMPOSE_PROJECT_NAME}-buggregator-server
    ports:
      - "8000:8000" # Web UI & Sentry/Ray API
      - "8025:1025" # SMTP Server (Mailcatcher)
      - "9912:9912" # Symfony VarDumper Server
      - "9913:9913" # Monolog Socket    
    environment:
      # Increase maximal memory allocations for processing large JSON requests
      - MAX_REQUEST_SIZE=104857600 # 100MB in bytes
      - HTTP_MAX_REQUEST_SIZE=104857600      
  database:
    build:
      context: "./.docker-settings/db"
    container_name: "${COMPOSE_PROJECT_NAME}-database"
    restart: "always"
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_INITDB_DIR}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${HOST_MACHINE_PHPMYADMIN_PORT}:80"
    depends_on:
      - database      